# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloguser',
            old_name='user',
            new_name='username',
        ),
    ]
