# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 01:57
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170408_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='\u680f\u76ee\u6807\u9898')),
                ('describtion', models.TextField(verbose_name='\u63cf\u8ff0')),
            ],
        ),
        migrations.AlterModelOptions(
            name='blogcontent',
            options={'verbose_name': '\u6587\u7ae0\u7ba1\u7406', 'verbose_name_plural': '\u6587\u7ae0\u7ba1\u7406'},
        ),
        migrations.AlterModelOptions(
            name='blogpage',
            options={'verbose_name': '\u9875\u9762\u7ba1\u7406', 'verbose_name_plural': '\u9875\u9762\u7ba1\u7406'},
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u5185\u5bb9'),
        ),
        migrations.AddField(
            model_name='blogcontent',
            name='cate',
            field=models.ManyToManyField(to='blog.Cate'),
        ),
    ]
