# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170410_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cate',
            options={'verbose_name': '\u5206\u7c7b\u7ba1\u7406', 'verbose_name_plural': '\u5206\u7c7b\u7ba1\u7406'},
        ),
        migrations.AlterModelOptions(
            name='myinfo',
            options={'verbose_name': '\u8bc4\u8bba\u7ba1\u7406', 'verbose_name_plural': '\u8bc4\u8bba\u7ba1\u7406'},
        ),
        migrations.AddField(
            model_name='blogcontent',
            name='ob',
            field=models.IntegerField(default=99, verbose_name='\u6392\u5e8f'),
        ),
        migrations.AddField(
            model_name='cate',
            name='ob',
            field=models.IntegerField(default=99, verbose_name='\u6392\u5e8f'),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='cate',
            field=models.ManyToManyField(to='blog.Cate', verbose_name='\u680f\u76ee'),
        ),
    ]
