# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_cate_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='display',
            field=models.BooleanField(default=True, verbose_name='\u662f\u5426\u663e\u793a'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='ob',
            field=models.IntegerField(default=99, verbose_name='\u6392\u5e8f'),
        ),
    ]
