# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170411_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='vname',
            field=models.CharField(default='', max_length=10, verbose_name='\u89c6\u56fe\u540d'),
        ),
    ]
