# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogcontent_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='\u83dc\u5355\u540d\u79f0')),
                ('url', models.CharField(max_length=255, verbose_name='\u5730\u5740')),
                ('display', models.BooleanField(default=True, verbose_name='\u662f\u5426\u663e\u793a')),
                ('ob', models.IntegerField(default=99, verbose_name='\u6392\u5e8f')),
            ],
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='vname',
            field=models.CharField(default='', max_length=10, verbose_name='\u9875\u9762\u5730\u5740'),
        ),
    ]
