# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20170414_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nav',
            options={'verbose_name': '\u5bfc\u822a\u7ba1\u7406', 'verbose_name_plural': '\u83dc\u5355\u7ba1\u7406'},
        ),
    ]
