# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_blogpage_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='img',
            new_name='image',
        ),
        migrations.AddField(
            model_name='blogcontent',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/images/'),
        ),
    ]
