# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_procate_producuct'),
    ]

    operations = [
        migrations.AddField(
            model_name='producuct',
            name='cate',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.ProCate', verbose_name='\u680f\u76ee'),
        ),
    ]
