# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_producuct_cate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procate',
            options={'verbose_name': '\u4ea7\u54c1\u5206\u7c7b', 'verbose_name_plural': '\u4ea7\u54c1\u5206\u7c7b'},
        ),
        migrations.AddField(
            model_name='producuct',
            name='pub_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='\u53d1\u5e03\u65f6\u95f4'),
            preserve_default=False,
        ),
    ]
